[package]
name = "rasp"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.7"
pest_derive = "2.7"
inkwell = { version = "0.5.0", features = ["llvm18-0"] }
rasp_runtime = { path = "../runtime" }
rpds = "1.1.0"
